spring:
  application:
    name: family-upload
  servlet:
    multipart:
      #设置单个文件大小
      max-file-size: @max.file.size@
      #设置总上传数据大小
      max-request-size: @max.request.size@
server:
  port: 18082