server:
  port: 8101
spring:
  application:
    name: VITALITY-Auth
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000
  profiles:
    include: database

jasypt:
  encryptor:
    password: TianQi